com:
  atomscat:
    freeswitch:
      amqp:
        commandsQueues: TAP.Commands
        eventsQueues: FS.Events
        loggingQueues: FS.Logging
      xml-curl:
#        auth-scheme: basic  # you need delete security dependency setting on pom.xml
        auth-scheme: digest  # you need add security dependency setting on pom.xml
        digest-enable: true
        credentials:
          username: muser
          password: mypass
      esl:
        inbound:
          defaultPassword: ClueCon
          performance: false
          performanceCostTime: 200
          servers:
            - host: 127.0.0.1
              port: 8021
              timeoutSeconds: 5
              routingKey: 127.0.0.1
            - host: 127.0.0.1
              port: 8021
              timeoutSeconds: 5
              routingKey: 127.0.0.1
          events:
            - all
        outbound:
          server:
            host: 127.0.0.1
            port: 8082
    opensips:
      event:
        server:
          host: 127.0.0.1
          port: 8081

logging:
  level:
    link: INFO


nacos:
  discovery:
    server-addr: 127.0.0.1:8848
    auto-register: true
    register:
      ip: 127.0.0.1
  config:
    server-addr: 127.0.0.1:8848
    bootstrap:
      enable: true
    data-id: example
    type: yaml
spring:
  application:
    name: softswitch-gateway
  redis:
    database: 1
    host: 127.0.0.1
    port: 6379
    password: Aa123456
    #redisson:
    #  file: classpath:redisson/redisson-dev.yaml

server:
  max-http-header-size: 102400
