com:
  atomscat:
    freeswitch:
      esl:
        inbound:
          defaultPassword: ClueCon
          performance: false
          performanceCostTime: 200
          servers:
            - host: 192.168.15.130
              port: 8021
              timeoutSeconds: 5
          events:
            - all
        outbound:
          server:
            host: 192.168.15.1
            port: 8082
    opensips:
      event:
        server:
          host: 192.168.15.1
          port: 8081

logging:
  level:
    link: INFO


nacos:
  discovery:
    server-addr: 192.168.15.130:8848
    auto-register: true
    register:
      ip: 192.168.15.1
  config:
    server-addr: 192.168.15.130:8848
    bootstrap:
      enable: true
    data-id: example
    type: yaml
spring:
  application:
    name: softswitch-gateway
  redis:
    database: 1
    host: 192.168.15.130
    port: 6379
    password: Aa123456
    #redisson:
    #  file: classpath:redisson/redisson-dev.yaml

server:
  max-http-header-size: 102400
