#com:
#  atomscat:
#    freeswitch:
#      amqp:
#        commandsQueues: TAP.Commands
#        eventsQueues: FS.Events
#        loggingQueues: FS.Logging
#      esl:
#        inbound:
#          defaultPassword: ClueCon
#          performance: false
#          performanceCostTime: 200
#          servers:
#            - host: 192.168.10.112
#              port: 8021
#              timeoutSeconds: 5
#            - host: 192.168.10.114
#              port: 8021
#              timeoutSeconds: 5
#          events:
#            - all
#        outbound:
#          server:
#            host: 192.168.10.116
#            port: 8082
#    opensips:
#      event:
#        server:
#          host: 192.168.10.116
#          port: 8081


spring:
  application:
    name: softswitch-gateway
  profiles:
    active: dev
  redis:
    database: 1
    host: 192.168.181.128
    port: 6379
    password: Aa123456
    #redisson:
    #  file: classpath:redisson/redisson-dev.yaml
  rabbitmq:
    host: 192.168.181.130
    port: 5672
    virtual-host: /
    username: guest
    password: guest
    listener:
      direct:
        acknowledge-mode: manual
      simple:
        acknowledge-mode: manual

server:
  max-http-header-size: 102400

logging:
  level:
    link: INFO

nacos:
  discovery:
    server-addr: 192.168.181.131:8848
    auto-register: true
    register:
      ip: 192.168.181.1
  config:
    server-addr: 192.168.181.131:8848
    bootstrap:
      enable: true
    data-id: example
    type: yaml